const data = [
  {
    id: 1,
    workType: "Plumbing",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: true,
    payAmount: 50,
    shortTitle: "Plumbing Assistance Needed",
    description: "We need urgent plumbing assistance at our location. The sink is leaking.",
    image: "image4.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 2,
    workType: "Electrician",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: true,
    payAmount: 80,
    shortTitle: "Electrician Needed",
    description: "We are looking for an electrician to install new lighting fixtures in our home.I'm in need of a robust, intuitive power app. This app will conduct detailed searches in a database that contains company qualifications. The search parameters are extensive, incorporating various factors",
    image: "image5.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 3,
    workType: "Gardening",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: true,
    payAmount: 40,
    shortTitle: "Gardening Help Required",
    description: "We need help with pruning and weeding in our garden.",
    image: "image1.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 4,
    workType: "Cleaning",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: true,
    payAmount: 60,
    shortTitle: "Emergency Cleaning Needed",
    description: "Urgently need someone to clean up after a party.",
    image: "image2.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 5,
    workType: "Moving",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: true,
    payAmount: 100,
    shortTitle: "Help with Moving",
    description: "Looking for movers to help with relocating furniture to a new apartment.",
    image: "image3.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 6,
    workType: "Painting",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: false,
    payAmount: 70,
    shortTitle: "Painter Needed",
    description: "We need a painter to paint the interior walls of our house.",
    image: "image1.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 7,
    workType: "Tutoring",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: false,
    payAmount: 50,
    shortTitle: "Math Tutor Required",
    description: "Looking for a math tutor to help with high school algebra.",
    image: "image2.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 8,
    workType: "Computer Repair",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: false,
    payAmount: 90,
    shortTitle: "Computer Repair Service Needed",
    description: "My computer is not booting up. Need someone to repair it.",
    image: "image3.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 9,
    workType: "Dog Walking",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: false,
    payAmount: 30,
    shortTitle: "Dog Walker Needed",
    description: "Looking for a reliable dog walker to walk our dog twice a day.",
    image: "image4.png",
    open: true,
    totalBidCount: 0
  },
  {
    id: 10,
    workType: "Photography",
    address: "Dhaka, Bangladesh",
    GPSCoordinates: { latitude: 23.811056, longitude: 90.407608 },
    emergency: false,
    payAmount: 120,
    shortTitle: "Photographer for Event",
    description: "Need a photographer for a birthday party event.",
    image: "image5.png",
    open: true,
    totalBidCount: 0
  },
];

export default data;

